require File.join(File.dirname(__FILE__), "spec_helper.rb")
require 'rake'
require 'rspec/core/rake_task'

desc "Run unit tests"
RSpec::Core::RakeTask.new(:unit) do |t|
    t.pattern = 'tests/unit/**/*_spec.rb'
    t.rspec_opts = File.read("spec.opts").chomp
end

desc "Run integration tests"
RSpec::Core::RakeTask.new(:integration) do |t|
    t.pattern = 'tests/integration/**/*_spec.rb'
    t.rspec_opts = File.read("spec.opts").chomp
end

task :default => [:unit]
